version: "2.2"
services:
 backend:
  image: shirlyne/yolobackend:1.0.0
  env_file:
    - ./backend/.env
  ports:
    - 5000:5000
  
 client:
  image: shirlyne/yoloclient:1.0.0
  depends_on:
    - backend
  ports:
   - 3000:3000
  
